# Generated by Django 5.2.7 on 2025-11-11 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Q_RECEIVED_LIKE', 'Question received a like'), ('Q_RECEIVED_ANSWER', 'Question received an answer'), ('A_RECEIVED_LIKE', 'Answer received a like'), ('A_MARKED_CORRECT', 'Answer was marked correct'), ('U_CHANGED_AVATAR', 'Changed avatar'), ('U_CHANGED_NAME', 'Changed name')])),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='users_activ_content_b971ef_idx')],
            },
        ),
    ]
