# Generated by Django 5.2.7 on 2025-11-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='displayed_name',
            new_name='display_name',
        ),
    ]
