# Generated by Django 5.2.7 on 2025-11-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfil',
            new_name='UserProfile',
        ),
    ]
