# Generated by Django 5.2.7 on 2025-11-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_userprofil_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
