# Generated by Django 5.2.7 on 2025-12-18 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_avatar_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
