upstream django_app {
    server 127.0.0.1:8000;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=qa_cache:10m inactive=60m;

server {
    listen 80;
    server_name qa.localhost;


    gzip on;
    gzip_types text/plain text/css application/javascript;
    gzip_comp_level 5;

    location /static/ {
        alias /home/nohy/QA-Website/static/;
        expires 30d;
    }

    location /media/ {
        alias /home/nohy/QA-Website/media/;
        expires 1d;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;

        proxy_cache qa_cache;
        proxy_cache_valid 200 10m;
        proxy_cache_valid 400 1m;
        add_header X-Proxy-Cache $upstream_cache_status;
    }
}
