# Generated by Django 5.2.7 on 2025-11-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_answer_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='author',
            new_name='user',
        ),
    ]
