# Generated by Django 5.2.7 on 2025-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_total',
            field=models.IntegerField(default=0),
        ),
    ]
