# Generated by Django 5.2.7 on 2025-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_answer_rating_total_question_rating_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
