# Generated by Django 5.2.7 on 2025-11-26 07:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_question_answer_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='qa.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка к ответу',
                'verbose_name_plural': 'Оценки к ответу',
            },
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='qa.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка к вопросу',
                'verbose_name_plural': 'Оценки к вопросу',
            },
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddConstraint(
            model_name='answervote',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_user_answer_vote'),
        ),
        migrations.AddConstraint(
            model_name='questionvote',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_vote'),
        ),
    ]
