# TODO Make central constants for the project

DEFAULT_PAGINATION_SIZE = 10
DEFAULT_BEST_QUESTIONS_LOOKBACK_DAYS = 3
POPULAR_TAGS_FETCH_LIMIT = 10
BEST_MEMBERS_FETCH_LIMIT = 5
RECENT_ACTIVITES_FETCH_LIMIT = 10
CACHE_TTL = 60 * 60 * 24
