MAX_TAG_NAME_LENGTH = 50
MAX_QUESTION_TAG_COUNT = 10

MIN_QUESTION_TITLE_LENGTH = 5
MAX_QUESTION_TITLE_LENGTH = 100
MIN_QUESTION_CONTENT_LENGTH = 25
MAX_QUESTION_CONTENT_LENGTH = 4000

MIN_ANSWER_CONTENT_LENGTH = 1
MAX_ANSWER_CONTENT_LENGTH = 1000

MAX_ANSWER_PREVIEW_LENGTH = 20

TAG_DELIMITER = "~"


LIKE = 1
DISLIKE = -1

VOTE_CHOICES = [
    (LIKE, "Like"),
    (DISLIKE, "Dislike"),
]
